[workspace]
members = [".", "macros"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autobins = false
description = "A collection of easy-to-use, beginner-friendly utilities for Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-dev.1"

[features]
std = []

[dependencies]
color-eyre = { version = "0.6.0" }
dotenv = "0.15.0"
eyre = "0.6.6"
ez-internal = { path = "./macros", version = "=0.0.2-dev.1" }
log = "0.4.14"
tracing = { features = ["log"], version = "0.1.29" }
tracing-error = { features = ["traced-error"], version = "0.2.0" }
tracing-subscriber = { features = ["env-filter"], version = "0.3.6" }

[profile.dev.package.backtrace]
opt-level = 3

[dev-dependencies]
compiletest_rs = { version = "0.7.1", features = ["tmp"] }
rustc_version = "0.4.0"

[workspace.metadata.release]
allow-branch = ["trunk", "main", "master"]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
