[workspace]
members = [".", "proc-macros", "examples"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autobins = false
description = "ez? wip."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-dev.5"

[features]
default = ["std"]
std = ["alloc"]
alloc = ["core"]
core = []

[dependencies]
ez--proc-macros = { path = "./proc-macros", version = "=0.0.2-dev.5"}

color-eyre = "0.6.0"
dotenv = "0.15.0"
eyre = "0.6.6"
tracing = { version = "0.1.30", features = ["log"] }
tracing-error = { version = "0.2.0", features = ["traced-error"] }
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }
fehler = "1.0.0"
tokio = { version = "1.16.1", features = ["rt", "macros", "fs", "signal", "process", "sync", "time", "parking_lot", "io-util", "io-std", "rt-multi-thread"] }

[profile.dev.package.backtrace]
opt-level = 3

[workspace.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
