[workspace]
members = [".", "macros"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
description = "A collection of easy-to-use, beginner-friendly utilities for Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-dev.1"

[features]
std = []

[dependencies]
boolinator = "2.4.0"
bytes = "1.1.0"
color-eyre = { version = "0.6.0" }
derive_more = "0.99.17"
dotenv = "0.15.0"
eyre = "0.6.6"
ez-internal = { path = "./macros", version = "=0.0.2-dev.1" }
ezio = "0.1.2"
fehler = "1.0.0"
indexmap = "1.8.0"
inherent = "1.0.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
macro_rules_attribute = "0.0.2"
noisy_float = "0.2.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
ordered-float = "2.10.0"
paste = "1.0.6"
rand = "0.8.4"
remain = "0.2.2"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
thousands = "0.2.0"
tokio = { version = "1.16.1", features = ["rt"] }
tracing = { features = ["log"], version = "0.1.29" }
tracing-error = { features = ["traced-error"], version = "0.2.0" }
tracing-subscriber = { features = ["env-filter"], version = "0.3.6" }
try-catch = "0.2.2"

[profile.dev.package.backtrace]
opt-level = 3

[dev-dependencies]
compiletest_rs = { version = "0.7.1", features = ["tmp"] }
rustc_version = "0.4.0"

[workspace.metadata.release]
allow-branch = ["trunk", "main", "master"]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
