[workspace]
members = [".", "macros"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autobins = false
description = "ez? wip."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-dev.3"

[features]
default = ["std", "pz"]
std = ["alloc"]
alloc = ["core"]
core = []
pz = []

[dependencies]
atty = "0.2.14"
boolinator = "2.4.0"
bytes = "1.1.0"
clap = "3.0.14"
color-eyre = "0.6.0"
crossbeam = "0.8.1"
derive_more = "0.99.17"
dotenv = "0.15.0"
dpc-pariter = "0.4.0"
eyre = "0.6.6"
ez-internal = { path = "./macros", version = "=0.0.2-dev.3" }
indexmap = "1.8.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
num-traits = "0.2.14"
parking_lot = "0.12.0"
paste = "1.0.6"
rand = "0.8.4"
rayon = "1.5.1"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["default", "deflate", "blocking", "gzip", "brotli", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
socket2 = "0.4.4"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["rt"] }
tracing = { features = ["log"], version = "0.1.30" }
tracing-error = { features = ["traced-error"], version = "0.2.0" }
tracing-subscriber = { features = ["env-filter"], version = "0.3.7" }

[profile.dev.package.backtrace]
opt-level = 3

[workspace.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
