[package]
name = "jeb"
publish = false
version = "0.0.0-2022.0.0"
edition = "2021"
authors = ["Jeremy Banks <_@jeremy.ca>"]

[dependencies]
boolinator = "2.4.0"
bytes = "1.1.0"
color-eyre = "0.5.11"
crossbeam = "0.8.1"
clap = { version = "3.0.0", features = ["derive", "cargo", "env", "regex", "unicode", "wrap_help"] }
derive_more = "0.99.17"
dotenv = "0.15.0"
eyre = "0.6.5"
getset = "0.1.2"
inherent = "1.0.0"
itertools = "0.10.3"
image = "0.23.14"
once_cell = "1.8.0"
parking_lot = "0.11.2"
paste = "1.0.6"
rand = "0.8.4"
thousands = "0.2.0"
tracing = { version = "0.1.29", features = ["log"] }
tracing-error = { version = "0.1.2", features = ["traced-error"] }
tracing-log = "0.1.2"
tracing-subscriber = "0.2.5"
tracing-unwrap = "0.9.2"
lazy_static = "1.4.0"
serde = { version = "1.0.132", features = ["derive"] }
macro_rules_attribute = "0.0.2"
num = { version = "0.4.0", features = ["std", "serde", "rand"] }
thiserror = "1.0.30"
num-derive = "0.3.3"

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.image]
opt-level = 3
