[workspace]
members = [".", "macros"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
description = "ez"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "weak"
repository = "https://github.com/jeremyBanks/weak"
version = "0.0.0-dev.1"

[dependencies]
num-derive = ">=0"
num-traits = ">=0"
weak-build-macros = { path = "./macros", version = "0.0.0-dev.1"}

[workspace.metadata.release]
allow-branch = ["trunk", "main", "master"]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"
