[workspace]
members = [".", "ez-internal", "ezze"]

[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autobins = false
description = "ez? wip."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-dev.4"

[features]
default = ["std"]
std = ["alloc"]
alloc = ["core"]
core = []
ze = [
    "std",
    "atty",
    "boolinator",
    "bytes",
    "crossbeam",
    "derive_more",
    "dpc-pariter",
    "indexmap",
    "itertools",
    "lazy_static",
    "num-traits",
    "parking_lot",
    "paste",
    "rand",
    "rayon",
    "regex",
    "reqwest",
    "reqwest/default",
    "reqwest/deflate",
    "reqwest/blocking",
    "reqwest/gzip",
    "reqwest/brotli",
    "reqwest/json",
    "serde",
    "serde/default",
    "serde_json",
    "socket2",
    "thiserror",
    "tokio",
    "tokio/default",
    "tokio/rt",
]

[dependencies]
ez-internal = { path = "./ez-internal", version = "=0.0.2-dev.4"}

color-eyre = "0.6.0"
dotenv = "0.15.0"
eyre = "0.6.6"
tracing = { version = "0.1.30", features = ["log"] }
tracing-error = { version = "0.2.0", features = ["traced-error"] }
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }

atty = { version = "0.2.14", optional = true }
boolinator = { version = "2.4.0", optional = true }
bytes = { version = "1.1.0", optional = true }
crossbeam = { version = "0.8.1", optional = true }
derive_more = { version = "0.99.17", optional = true }
dpc-pariter = { version = "0.4.0", optional = true }
indexmap = { version = "1.8.0", optional = true }
itertools = { version = "0.10.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }
num-traits = { version = "0.2.14", optional = true }
parking_lot = { version = "0.12.0", optional = true }
paste = { version = "1.0.6", optional = true }
rand = { version = "0.8.4", optional = true }
rayon = { version = "1.5.1", optional = true }
regex = { version = "1.5.4", optional = true }
reqwest = { version = "0.11.9", optional = true }
serde = { version = "1.0.136", optional = true }
serde_json = { version = "1.0.78", optional = true }
socket2 = { version = "0.4.4", optional = true }
thiserror = { version = "1.0.30", optional = true }
tokio = { version = "1.16.1", optional = true }

[profile.dev.package.backtrace]
opt-level = 3

[workspace.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
