[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
description = "ez? wip."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-ez.0"

[dependencies]
ez-proc-macro = { path = "../ez-proc-macro", version = "=0.0.2-ez.0"}
ez-internal = { path = "../ez-internal", version = "=0.0.2"}
