[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autoexamples = false
description = "wip"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
rust-version = "1.59.0"
version = "0.0.2-ez.6"

[dependencies]
ez-internal = { path = "../ez-internal", version = "=0.0.2-ez.6"}
ez-proc-macro = { path = "../ez-proc-macro", version = "=0.0.2-ez.6"}

[dev-dependencies]
tokio = { version = "1.16.0", features = ["full"] }
trybuild = "1.0.56"

[package.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"
