[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
autoexamples = false
description = "A collection of easy-to-use, beginner-friendly utilities for Rust."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ez"
repository = "https://github.com/jeremyBanks/ez"
rust-version = "1.59.0"
version = "0.0.4-dev"

[dependencies]
eyre = "0.6.6"
ez-impl = { path = "../ez-impl", version = "=0.0.4-dev"}
ez-proc-macro = { path = "../ez-proc-macro", version = "=0.0.4-dev"}

[dev-dependencies]
eyre = "0.6.6"
tokio = { version = "1.16.0", features = ["full"] }
trybuild = "1.0.56"

[package.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
