[package]
authors = ["Jeremy Banks <_@jeremy.ca>"]
description = "internal"
documentation = "https://docs.rs/ez"
edition = "2021"
homepage =  "https://crates.io/crates/ez"
license = "MIT OR Apache-2.0"
name = "ez-proc-macro"
repository = "https://github.com/jeremyBanks/ez"
version = "0.0.2-ez.0"

[lib]
proc-macro = true

[dependencies]
ez-internal = { version = "0.0.2-ez.0", path = "../ez-internal" }

quote = "1.0.15"
syn = { version = "1.0.86", features = ["full"] }
proc-macro2 = "1.0.36"

