cargo-features = ["workspace-inheritance"]

[package]
description = "a loop-style macro for local code duplication"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "doop"
repository = "https://github.com/jeremyBanks/ez"
rust-version = "1.59.0"
version = "0.0.7-dev"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.1.5"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
quote = "1.0.15"
syn = { version = "1.0.86", features = ["full", "visit", "visit-mut", "fold", "derive", "parsing", "printing", "clone-impls", "extra-traits", "proc-macro"] }
indexmap = "1.8.0"
derive_more = "*"
inherent = "*"

[package.metadata.release]
consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
shared-version = true
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"
