[package]
edition = "2021"
name = "ez-examples"
publish = false
version = "0.0.0"

[dev-dependencies]
ez = { path = "../ez" }
tokio = { version = "*", features = ["full"] }

[package.metadata.release]
release = false
