on: [workflow_dispatch, pull_request]
name: rust
jobs:
  rust:
    strategy:
      matrix:
        include:
        - name: maximum versions
          rust_toolchain: stable
        - name: minimum versions
          rust_toolchain: 1.59.0
          cargo_flags: -Z unstable-options -Z minimal-versions
          bootstrap: RUSTC_BOOTSTRAP=1
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
      - run: ${{ matrix.bootstrap }} cargo +${{ matrix.rust_toolchain }} ${{ matrix.cargo_flags }} build --all
      - run: ${{ matrix.bootstrap }} cargo +${{ matrix.rust_toolchain }} ${{ matrix.cargo_flags }} clean
      - run: ${{ matrix.bootstrap }} cargo +${{ matrix.rust_toolchain }} ${{ matrix.cargo_flags }} test --all
      - run: ${{ matrix.bootstrap }} cargo +${{ matrix.rust_toolchain }} ${{ matrix.cargo_flags }} doc --all
